DEVICE_ID = "jetson-nano-01"
CAMERA_ID = 0

FOG_SERVER_URL = "http://10.13.247.110:5001/alert"

ALERT_COOLDOWN_SECONDS = 5
REQUEST_TIMEOUT_SECONDS = 3
ALERT_RETRY_COUNT = 2
CONFIDENCE_THRESHOLD = 0.30
DETECTION_MEMORY_SECONDS = 1.0

MOCK_THREAT_CLASSES = {
    "banana": "mock_gun_threat",
    "cucumber": "mock_knife_threat",
}
